kind: Deployment
apiVersion: apps/v1
metadata:
  name: fishtest
  labels:
    app: fishtest
    app.kubernetes.io/component: fishtest
    app.kubernetes.io/instance: fishtest
    app.kubernetes.io/name: fishtest
    app.kubernetes.io/part-of: fishtest
    app.openshift.io/runtime: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishtest
  template:
    metadata:
      labels:
        app: fishtest
        deployment: fishtest
    spec:
      containers:
        - name: fishtest
          image: docker.io/toughiq/fishtest:latest
          envFrom:
            - secretRef:
                name: fishtest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
